sudo: false
language: node_js
node_js:
  - "8"
  - "10"
  - "node" # latest stable Node.js release

cache:
  directories:
    - "node_modules" # cache the modules for faster build

script:
  - npm install
  - npm run eslint
