os:
  - linux
  - windows
sudo: false
language: node_js
node_js:
  - "8"
  - "10"
  - "node" # latest stable Node.js release

cache: npm

script:
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      git config core.autocrlf false && git add --renormalize . && git reset --hard;
    fi
  - npm install
  - npm run eslint
  - npm test
